### ISSUE TITLE
Show "Pumpen"-Status, link to OSM

### ISSUE THREAD

**Issue by tordans** [technologiestiftung/giessdenkiez-de#170]
It's great to see the OSM data for Berliner Pumpen used for this app.

Based on https://www.openstreetmap.org/note/2204622, I think some improvements would be helpful for the users:

# Idea 1: Show status in the app

The pump-status ist tracked with `pump:status=broken` `pump:status=ok` and others, see https://wiki.openstreetmap.org/wiki/DE:Berliner_Stra%C3%9Fenbrunnen

This status could be shown in the app.
I suggest to also show the `check_date=2020-06-06` to indicate, when the status has last been checked in OSM.

# Idea 2: Link to OSM

Since the position on the map is quite rough, it would be nice to link to the OSM object, so that users might see that they can comment more directly and find it and maybe update it.
See https://www.openstreetmap.org/note/2204622 for example, where the comment note was place a bit away from the pump-node (https://www.openstreetmap.org/node/760002892).

It might also be helpful to link to https://wiki.openstreetmap.org/wiki/DE:Berliner_Stra%C3%9Fenbrunnen which explains how the Pumpen are mapped in OSM-Berlin.

**Comment by fabianmoronzirfas** [comment]
Hi @tordans Thanks for the suggestion. The pumps data set is pretty basic currently. See [the geojson](https://github.com/technologiestiftung/tsb-trees-frontend/blob/master/public/data/pumps.geojson). 

I guess idea 1 having them and keeping them up to date would need the following things.

Automated process of

- aggregation (from where?) 
- and (maybe) cleaning
- storing on a public location where we can access it (AWS s3?)

I think this should not be done in this repo. This would be a something the [harvester](https://github.com/technologiestiftung/dwd-radolan-tree-harvester/) should do on a daily basis.

Idea 2 is more a thing for the FAQ and some additional text. Is there a way we can link directly with an ID to a pump?

@fdnklg @sebastian-meier how was the pumps dataset created (also related to #132 )?

**Comment by fe60** [comment]
> I guess idea 1 having them and keeping them up to date would need the following things.
> Automated process of
>     * aggregation (from where?)

@fabianmoronzirfas  You could use the Overpass API [1]. They offer a web frontend to get familiar with the API [2]. Beside seeing the hits on a map, you can switch to the xml-data of the result set.

This query should provide the data you are looking for.
```
area
  [boundary=administrative]
  [admin_level=4]
  ["name"="Berlin"]->.searchArea;
node
  [man_made=water_well](area.searchArea);
out;
```


[1] https://wiki.openstreetmap.org/wiki/Overpass_API
[2a] https://wiki.openstreetmap.org/wiki/Overpass_turbo
[2b] https://overpass-turbo.eu/s/Vtd (incl. query mentioned above)

**Comment by fabianmoronzirfas** [comment]
@fe60 Thanks. Very nice. So the following call gives we a xml that I can convert to geojson and map it? Could be part of the build or could be run on a daily basis.

    curl "https://overpass-api.de/api/interpreter?data=area%0A%20%20%5Bboundary%3Dadministrative%5D%0A%20%20%5Badmin_level%3D4%5D%0A%20%20%5B%22name%22%3D%22Berlin%22%5D-%3E.searchArea%3B%0Anode%0A%20%20%5Bman_made%3Dwater_well%5D%28area.searchArea%29%3B%0Aout%3B%0A"

**Comment by fe60** [comment]
@fabianmoronzirfas The API offers the option to ask for different output formats [1]. Unfortunately it does not provide the data as GeoJSON. But there is a command line tool doing the required conversion [2].

[1] https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Output_Format_.28out:.29
[2a] https://wiki.openstreetmap.org/wiki/Overpass_turbo/GeoJSON
[2b] https://github.com/tyrasd/osmtogeojson

**Comment by fe60** [comment]
> # Idea 1: Show status in the app
> 
> The pump-status ist tracked with `pump:status=broken` `pump:status=ok` and others, see https://wiki.openstreetmap.org/wiki/DE:Berliner_Stra%C3%9Fenbrunnen
> 
> This status could be shown in the app.
> I suggest to also show the `check_date=2020-06-06` to indicate, when the status has last been checked in OSM.

@tordans `survey:date` seems to be the better choice compared to `check_date`.
https://wiki.openstreetmap.org/wiki/Key:survey:date

**Comment by tordans** [comment]
> @tordans `survey:date` seems to be the better choice compared to `check_date`.
> 
> https://wiki.openstreetmap.org/wiki/Key:survey:date

There is no consensus on either and the local guideline uses check_date (https://wiki.openstreetmap.org/wiki/DE:Berliner_Stra%C3%9Fenbrunnen) so I recommend sticking with it - for this tagging schema.

**Comment by SupaplexOSM** [comment]
*subscribe*

I recommend to use the "description=Berliner Straßenbrunnen" tag to query the public Berlin water pumps from the OSM data base (http://overpass-turbo.eu/s/PQ3). Some month ago I cleaned up the OSM data and this query works reliably. Otherwise you get many pumps on private property like garden pumps or historic water wells. I regularly check the database to maintain consistency.

"survey:date" might be the better choice following the OSM wiki - I'll update the OSM Berlin pump guidelines accordingly. In any case, different variants should be considered for queries.

**Comment by Wikinaut** [comment]
Siehe auch https://overpass-turbo.eu/s/VLo

**Comment by tordans** [comment]
Hi! I am sad to see that you switched away from using OSM in #188. 

Is there a place that explains the reason for this change; or could you explain it here?

https://github.com/technologiestiftung/giessdenkiez-de/commit/9902ae908a76cb58fdfc7d0a08587af551237935 suggest that the data from the city is more complete and accurate. I would love to see the data comparison for this, so we can improve OSM as well. In my experience, the city data is at best as incomplete as OSM. But it cannot be updated by the community.

FYI @SupaplexOSM

**Comment by fabianmoronzirfas** [comment]
@tordans we will have a meeting next week where we will review that decision. I think the reason was that the dataset coming from the WFS service was more complete than the current data we had. As I remember it @Lisa-Stubert told me that the official data was used to update the OSM data. So we might switch back.

**Comment by tordans** [comment]
> @fabianmoronzirfas The API offers the option to ask for different output formats [1]. Unfortunately it does not provide the data as GeoJSON. But there is a command line tool doing the required conversion [2].

I just saw that in https://github.com/jbelien/osm-compare/blame/master/routes/compare.js#L31 they use https://www.npmjs.com/package/osmtogeojson to create a geojson from osm-overpass-data.

**Comment by tordans** [comment]
Thanks @fabianmoronzirfas 
> I think the reason was that the dataset coming from the WFS service was more complete than the current data we had. As I remember it @Lisa-Stubert told me that the official data was used to update the OSM data. So we might switch back.

Yes, I heard from @SupaplexOSM that he is already talking to Lisa-Stubert.

I looked into the data with https://github.com/tordans/osm_conflate/commit/cebb428121b7c40ac656bf6732230381261b4362. From a first glance it looks like there is more data in the Randbezirke (green=missing in OSM), but also a bit of missing data (red=missing in Citydata).

![image](https://user-images.githubusercontent.com/111561/90068863-aa437c80-dcf1-11ea-9adb-d2c71bba009f.png)

I send the results to @SupaplexOSM to have a look. We might need to create a https://maproulette.org/ challenge to add the data to OSM. (https://pic4review.pavie.info/#/ is no option unfortunately for this data and use case.)

**Comment by Lisa-Stubert** [comment]
@tordans  thanks for the analysis of the different data situation. Exactly, we switched to the official data at that time, because these contain considerably more pumps and because we actually try to use as much open data of the public administration as possible. We are already in discussion with the administration and are trying to find out whether the quality of the data can be improved. Unfortunately this will not happen so quickly. Since there is so much interest in the functionality of the pumps of the Gieß den Kiez users, it makes sense to switch back to OSM. But it would be nice if the OSM community could enter the missing pumps from time to time. I'm already talking to @SupaplexOSM about this, but he has noted that due to the strict regulations of OSM, adding pumps is not so fast. I have no experience with maproulette, but it might be a good idea.

**Comment by fabianmoronzirfas** [comment]
@all in this thread. Just a update. We are working on a script that aggregates the data from OSM to create our geojson.

We will run this on a weekly schedule. As soon as it is ready we will open source it and link it here.

**Comment by fabianmoronzirfas** [comment]
Here is the harvester https://github.com/technologiestiftung/giessdenkiez-de-osm-pumpen-harvester/

**Comment by fabianmoronzirfas** [comment]
Hey we added the status of the pumps on hover and we'd love to get some feedback. You can see a deploy preview here https://deploy-preview-218--internetoftrees.netlify.app/

**Comment by SupaplexOSM** [comment]
Nice! Some ideas for small adjustments - however, they go into detail and only affect very few locations:
1) There is the status "out_of_order" (currently 3x in Berlin) which could be displayed as a bright point (category "not functional") - e.g. https://www.openstreetmap.org/node/6249473226.
2) In rare cases the pumps are not open accessable to the public (OSM-Tag: access=private). Then they could also be shown in the light category with a corresponding note "No public access"/"Nicht öffentlich zugänglich" (see e.g. https://www.openstreetmap.org/node/5538995537)
3) There may be wells that do not belong to the network of Berlin street / emergency water wells, but are still accessible to the public (OSM-query "water_well=pump" + "access=yes" or "access=permissive"). These could possibly also appear on the map. However, I can currently only find one suitable case: https://www.openstreetmap.org/node/7851278239 (a freely accessible pump built on private initiative)

Now the only thing missing is the possibility for users to be able to play back a status report :) Maybe you have the capacity for a narrow solution someday like a online table or a mini-feedback-form. I'm happy to add messages/reports to the OSM database.

**Comment by fabianmoronzirfas** [comment]
@SupaplexOSM thanks for the feedback. 1. 2. 3. sound like edge cases. I added the `out_of_order` pumps and the `missing_beam` to the `defekt` [category](https://github.com/technologiestiftung/giessdenkiez-de-osm-pumpen-harvester/blob/c5df6b6e412d5955815da692fe6ead3bb07ea078/fetch_osm_pumps.py#L99-L108) so these will be covered.

Getting feedback back in would be awesome. We get a lot of feedback about missing trees and trees on private property. So there is a demand on sending information upstream again. This could also contain information about the pumps states, but we will have to add this to the backlog. Since we are on feature freeze now.

**Comment by Lisa-Stubert** [comment]
Perhaps we could set up a channel in our Gieß-den-Kiez-Slack as a quick but helpful alternative to a feedback form. Then we would also add a section "How can I report broken/missing pumps or missing information about pumps?" to the FAQ's and refer to the Slack-channel. Unfortunately we don't have time to maintain the channel/process the reports, but for the OSM community it would be a possibility to get information?

**Comment by SupaplexOSM** [comment]
Would be a good solution for now. I could transfer the data if someone reports something.

**Comment by fabianmoronzirfas** [comment]
The pumps are online. Thanks 2 everyone for the effort.
