### ISSUE TITLE
Color scale is unintuitive

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/giessdenkiez-de#208]
We have a very dry period and the trees are in a nice pale green. We've got several messages from the community, that the scale is wired.

We should change that.

What could be the right color? 
The colors don't represent the heat, they represent the amount of rain that fell in the last 30 days.

@jvolker @dnsos @julizet any ideas what we could use?

**Comment by jvolker** [comment]
> The colors don't represent the heat, they represent the amount of rain that fell in the last 30 days.

Intuitively, I was always thinking the colours would represent how desperately the trees need watering. But is that something that can actually be derive from the rain and tree type/age data?

I would suggest good old red, yellow to green (maybe some fancy shades): 
- Red: "Super dry. Tree desperately needs water."
- Yellow: "Half dry. Could use some watering"
- Green: "All good. No watering needed.".

**Comment by fabianmoronzirfas** [comment]
> I would suggest good old red, yellow to green (maybe some fancy shades):
> 
>     * Red: "Super dry. Tree desperately needs water."
> 
>     * Yellow: "Half dry. Could use some watering"
> 
>     * Green: "All good. No watering needed.".

Yes that was my initial thought to.

**Comment by maximilianpalm** [comment]
Same thing here, I think that:
(a) the coloring is a little optimistic at the moment, and
(b) the colors should indicate how "thirsty" each tree is.
For the latter, you could factor in all kinds of weather and terrain data like rainfall, temperature, cloud coverage, solar radiation, humidity and soil, as well as data for the individual trees like their age. To make it easier, I'm trying to find out if it's possible to use existing models like "UFZ Dürremonitor". Once I get some answers, I will open a separate issue.
In the meantime, maybe it's possible to change the color scale a little towards red and maybe also link the tree and the rainfall data, so that an established tree appears greener than a young tree right next to it.

**Comment by fabianmoronzirfas** [comment]
In the upcoming version we changes the color scale

**Comment by julizet** [comment]
deploy preview of [PR](https://github.com/technologiestiftung/giessdenkiez-de/pull/197) looks good to me
Issue can be closed, if fine for you @fabianmoronzirfas
