### ISSUE TITLE
Feature Request: Mark trees as "under-watered"

### ISSUE THREAD

**Issue by maximilianpalm** [technologiestiftung/giessdenkiez-de#209]
## Background: Why this issue? 
If I see a tree that urgently needs water, e.g. because the leaves are curling up and are becoming yellow, I would like to have a possibility to mark that tree for other users in case I am not able to water it myself. I had this problem two years ago on my way to work, although I think in that case I noticed it too late. I hope others as well as myself today are more vigilant.

## Deliverables: How to fix the issue?
As a registered user, I want to mark trees as under-watered so that other users can see it and water the tree.
Acceptance criteria:
- In the tree detail view, there is a button "Baum braucht dringend Wasser" that registered users can click (with confirmation step "Bist du sicher ...?").
- After marking a tree as under-watered, a label is visible in the tree detail view that explains that a user marked it and that it should be watered urgently.
- A tree marked as under-watered appears on the map as either completely red or with a red circle around it's otherwise designated color.

## Output: Gain of fixing the issue?
Dying trees can possibly be saved, even if the people noticing the problem are not able to fix it themselves.

## Issue creation checklist
- [ ] I have attached one of the priority labels `HIGH`, `MIDDLE`, `LOW`
- [ ] I have attached other labels with regard to the issues purpose (i.e.`enhancement`, `bug`, `community feedback`)

**Comment by Lisa-Stubert** [comment]
A good idea in principle. We talked about this topic with the experts on tree irrigation from the Senatsverwaltung für Umwelt and the Grünflächenämter. They told us, that it is very difficult to make a statement about whether a tree is really acutely under drought stress. Some trees in Berlin are already very old and are slowly reaching the end of their life. Others are afflicted with diseases. According to the experts, it is hardly possible for a layperson to see why the tree is suffering. The damage that can be seen on the trees today is partly a long-term effect of the last 2 dry years, which are only now becoming visible.
Watering is therefore good, but the experts in Berlin are worried that trees will be overwatered because of such recommendations. I think we should therefore refrain from such a feature at the current level of information that the application offers or consider a Feature to report this trees to the Grünflächenämter, so that experts can check the tree, but this would be another project.

**Comment by HenrietteN** [comment]
@maximilianpalm Nice idea. Adding to Lisa's comment tho, it might be difficult to actually pin point trees in need for water only by visual observation, plus differs on the range of botanical knowledge. 
In this regard, in the updated version we have added the following features: color code indication of trees in need for watered based on their age and the received water. Of course this could further be improved by species, AR features (#244) or implementing satelite data. 
Furthermore, you can now send a the tree via its hyperlink to others, and directly contact other users via e-mail. Maybe that already helps a little bit for the coordination. 

I hope this helps. :)
