### ISSUE TITLE
Offer more water quantities to chose from

### ISSUE THREAD

**Issue by sonnenhelli** [technologiestiftung/giessdenkiez-de#352]
## Background: Why this issue? 
Right now it is only possible to chose between 5, 10, 25 and 50 litres. I regularly water with 30 and 15 litres and it would be great to have more choices.
-

## Deliverables: How to fix the issue?
Add more choices: 15, 20, 30, 40
-

## Output: Gain of fixing the issue?
The amount of watering would be more correct.
-

## Issue creation checklist
- [x] I have attached one of the priority labels `HIGH`, `MIDDLE`, `LOW`
- [x] I have attached other labels with regard to the issues purpose (i.e.`enhancement`, `bug`, `community feedback`)
middle
enhancement, community feedback

**Comment by yannickoo** [comment]
An alternative could be a number input which allows submitting values from 5 up to 100.

**Comment by vogelino** [comment]
Hi! Thx @sonnenhelli for the issue and @yannickoo for the suggestion! We have an eye on this issue but we have higher prioritized tasks before us right now. Feel free to add a PR with your suggestion, we will make sure to review it as soon as possible! Thank you for your understanding!

**Comment by julizet** [comment]
Hi @sonnenhelli & @panketaucher, 
we took care of a new water modal in spring 2022. The new water modal offers users to select a date (see [this commit](https://github.com/technologiestiftung/giessdenkiez-de/commit/df9adcb188d284138dff787e1723096898814068)) and an individual water amount (see [this commit](https://github.com/technologiestiftung/giessdenkiez-de/commit/84aa1d362bdc971123f0583dc7dc21e5656608e1)).

Since late April 2022 users can:
- pick a **date** for their waterings (the date cannot be older than six months and cannot be in the future)
- type in an **individual water amount** (the water amount cannot be 0 or equal or greater than 1000)

Thanks for your sharing your insights and suggestions.
