### ISSUE TITLE
Position of disadopt tree button.

### ISSUE THREAD

**Issue by panketaucher** [technologiestiftung/giessdenkiez-de#385]
Good evening.

I water trees with amounts that proceed 50 litres regularly. The max volume with GdK is 50 litres. So I have to click the 'Water tree' button multiple times and wait until all the data and the diagram is updated. The 'last watered' list gets longer and pushes the buttons below it one line further. Thus, the 'Disadopt tree' button gets in position of the 'Water tree' button. 
I would recommend to change the order of the buttons to avoid disadopting trees accidently.

Greetings
panketaucher

**Comment by julizet** [comment]
Hi @panketaucher, 
we currently updated the order the buttons so that now the "Ich habe gegossen" button is above the "Adoption aufheben" button. Furthermore, latest waterings are now shown at the very top of the list. Please see the code changes here https://github.com/technologiestiftung/giessdenkiez-de/commit/f57c1f43aa596f83db396e8aa4fcec4328df4fc3
Thank you very much for reporting.
